language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - docker version
  - docker-compose version

before_script:
  - pip install docker-compose
  - docker-compose run --user='root' app chmod -R 777 .

script:
  # - docker-compose run app sh -c "python manage.py test && flake8"
  - docker-compose run app sh -c "coverage run --source=. manage.py test"

after_script:
  - coverage xml

after_success:
  # Generates coverage report, public repo using Travis:
  # Source: https://dev.to/j0nimost/using-codecov-with-travis-ci-pytest-cov-1dfj
  # - codecov
  #
  # Source: https://hackernoon.com/integrating-travis-ci-and-codecov-into-a-python-based-project-6f658074ff63
  - bash < (curl -s https://codecov.io/bash)