language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - docker version
  - docker-compose version

before_script:
  - pip install docker-compose
  - pip install codecov

script:
  - docker-compose run --rm $(bash <(curl -s https://codecov.io/env)) -u root app sh -c "pip install codecov && python manage.py test && flake8 && bash <(curl -s https://codecov.io/bash)"

# Push the results back to codecov
after_success:
  # - codecov
