language: python
python:
  - "3.6"

services:
  - docker

before_script:
  - pip install docker-compose
  - pip install pytest
  - pip install pytest-cov #This plugin produces coverage reports
  - pip install codecov #install codecov

script:
  # - docker-compose run app sh -c "python manage.py test && flake8"
  - docker-compose run app sh -c "pytest --cov-config=.coveragerc --cov-report term-missing --cov && flake8"  # check test coverage with pytest-cov

after_success:
  # Generates coverage report, public repo using Travis:
  # Source: https://dev.to/j0nimost/using-codecov-with-travis-ci-pytest-cov-1dfj
  - codecov