language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - docker version
  - docker-compose version

before_script:
  - pip install docker-compose

script:
  # - docker-compose run --rm $(bash <(curl -s https://codecov.io/env)) -u root app sh -c "python manage.py test && flake8"
 - docker-compose run app sh -c "python manage.py test && flake8"
