language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - docker version
  - docker-compose version

before_script:
  - pip install docker-compose
  - docker-compose run --user='root' app chmod -R 777 .

script:
  # - docker-compose run app sh -c "python manage.py test && flake8"
  - ci_env="bash <(curl -s https://codecov.io/env)"
  - ci_post_cov="bash <(curl -s https://codecov.io/bash)"
  - docker-compose run app sh -c "$ci_env && coverage run --source=. manage.py test && $ci_post_cov"

after_script:
  - coverage xml

after_success:
  # Generates coverage report, public repo using Travis:
  # Source: https://dev.to/j0nimost/using-codecov-with-travis-ci-pytest-cov-1dfj
  - codecov