language: python
python:
  - "3.6"

services:
  - docker

before_script:
  - pip install docker-compose
  - docker-compose run --user='root' app chmod -R 777 .

script:
  # - docker-compose run app sh -c "python manage.py test && flake8"
  - docker-compose run app sh -c "coverage run --source=. manage.py test"

after_success:
  # Generates coverage report, public repo using Travis:
  # Source: https://dev.to/j0nimost/using-codecov-with-travis-ci-pytest-cov-1dfj
  - codecov